---
- name: >
    Installs PHP, WP-CLI, MariaDB, WordPress, PHP-FPM, Nginx, Apache2, HHVM,
    Redis. Disables the software from starting on boot and stops them.
    Run other playbooks to set up the server for serving, for example:
    wordpress_basic.yml with nginx_php-fpm.yml: WordPress with default theme
    served on Nginx with PHP-FPM.

  hosts: webservers
  remote_user: root

  roles:
    - common
    - mariadb
    - wp-cli
    - wordpress-install
    - nginx
    - hhvm

