---
- name: Add MariaDB MySQL apt-key
  apt_key: url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search={{ keyserver_fingerprint }}" state=present

- name: Add MariaDB MySQL deb and deb-src
  apt_repository: repo="{{ item }}" state=present
  with_items:
  - "deb http://{{ mirror }}/mariadb/repo/{{ version }}/{{ ansible_distribution | lower }} {{ mariadb_dist | default(ansible_distribution_release) }} main"
  - "deb-src http://{{ mirror }}/mariadb/repo/{{ version }}/{{ ansible_distribution | lower }} {{ mariadb_dist | default(ansible_distribution_release) }} main"

- name: Install MariaDB MySQL server
  apt: name=mariadb-server state=present update_cache=yes

- name: Start MariaDB MySQL Server
  service: name=mysql state=started enabled=true


- name: Delete anonymous MySQL server user for current hostname
  mysql_user: user=""
              host="{{ ansible_hostname }}"
              state=absent
              login_user=root
              login_password="{{ mysql_root_password }}"

- name: Remove the test database
  mysql_db: name=test
            state=absent
            login_user=root
            login_password="{{ mysql_root_password }}"
